import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { PageHeader } from "@/components/commons/primitives";
import { StatusBadge } from "@/components/commons/StatusBadge";
import { outputs, deptLabel } from "@/lib/commons/prototype-data";

export function RecentPage() {
  return (
    <>
      <PageHeader
        title="Recent outputs"
        description="Finished and in-flight work Jo from has compiled across your company."
      />
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {outputs.map((o) => (
          <Card key={o.id} className="gap-3">
            <CardHeader>
              <CardTitle className="text-base">{o.title}</CardTitle>
              <CardDescription>{o.type} · {deptLabel(o.department)}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-2 text-sm">
              <div className="flex justify-between"><span className="text-muted-foreground">Generated by</span><span className="font-medium">{o.generatedBy}</span></div>
              <div className="flex justify-between"><span className="text-muted-foreground">When</span><span className="font-medium">{o.timestamp}</span></div>
              <Separator />
              <div>
                <p className="mb-1.5 text-xs text-muted-foreground">History</p>
                <div className="flex flex-wrap items-center gap-1 text-xs">
                  {o.history.map((h, i) => (
                    <span key={i} className="flex items-center gap-1">
                      {i > 0 && <span className="text-muted-foreground/40">→</span>}
                      <span className="rounded bg-accent px-1.5 py-0.5">{h}</span>
                    </span>
                  ))}
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <StatusBadge kind={o.statusKind} label={o.statusLabel} />
            </CardFooter>
          </Card>
        ))}
      </div>
    </>
  );
}
